[package]
name = "todo"
version = "0.1.1"
authors = ["32byte <xlebedenko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"

[dependencies]
text_io = "0.1.8"
home = "0.5.3"
